name: konfig-push-openapi-spec
on:
  push:
    branches:
      # 1) Replace with name of your production branch
      - main
jobs:
  konfig-push-openapi-spec:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.0.40
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in "~/.npm" on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-konfig-push-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Push OpenAPI Spec
        # 2) Replace "api.yaml" with path to OAS
        # 3) Replace "konfig-dev" with owner of SDK repository
        # 4) Replace "acme-sdks" with name of repository
        run: konfig push -s openapi.yaml -o konfig-dev -r newscatcher-sdks
